# Termux Bootstrap - Default TMUX Configuration

# Prefix
unbind C-b
set -g prefix C-a
bind C-a send-prefix

# Split panes
bind | split-window -h
bind - split-window -v

# Mouse support
set -g mouse on

# History
set -g history-limit 10000
